var PERF1 = exports = 
  { "access": "acess"
  , "accessing": "accesing"
  , "accommodation": "accomodation acommodation acomodation"
  , "account": "acount"
  , "address": "adress adres"
  , "addressable": "addresable"
  , "arranged": "aranged arrainged"
  , "arrangeing": "aranging"
  , "arrangement": "arragment"
  , "articles": "articals"
  , "aunt": "annt anut arnt"
  , "auxiliary": "auxillary"
  , "available": "avaible"
  , "awful": "awfall afful"
  , "basically": "basicaly"
  , "beginning": "begining"
  , "benefit": "benifit"
  , "benefits": "benifits"
  , "between": "beetween"
  , "bicycle": "bicycal bycicle bycycle"
  , "biscuits": "biscits biscutes biscuts bisquits buiscits buiscuts"
  , "built": "biult"
  , "cake": "cak"
  , "career": "carrer"
  , "cemetery": "cemetary semetary"
  , "centrally": "centraly"
  , "certain": "cirtain"
  , "challenges": "chalenges chalenges"
  , "chapter": "chaper chaphter chaptur"
  , "choice": "choise"
  , "choosing": "chosing"
  , "clerical": "clearical"
  , "committee": "comittee"
  , "compare": "compair"
  , "completely": "completly"
  , "consider": "concider"
  , "considerable": "conciderable"
  , "contented": "contenpted contende contended contentid"
  , "curtains": "cartains certans courtens cuaritains curtans curtians curtions"
  , "decide": "descide"
  , "decided": "descided"
  , "definitely": "definately difinately"
  , "definition": "defenition"
  , "definitions": "defenitions"
  , "description": "discription"
  , "desiccate": "desicate dessicate dessiccate"
  , "diagrammatically": "diagrammaticaally"
  , "different": "diffrent"
  , "driven": "dirven"
  , "ecstasy": "exstacy ecstacy"
  , "embarrass": "embaras embarass"
  , "establishing": "astablishing establising"
  , "experience": "experance experiance"
  , "experiences": "experances"
  , "extended": "extented"
  , "extremely": "extreamly"
  , "fails": "failes"
  , "families": "familes"
  , "february": "febuary"
  , "further": "futher"
  , "gallery": "galery gallary gallerry gallrey"
  , "hierarchal": "hierachial"
  , "hierarchy": "hierchy"
  , "inconvenient": "inconvienient inconvient inconvinient"
  , "independent": "independant independant"
  , "initial": "intial"
  , "initials": "inetials inistals initails initals intials"
  , "juice": "guic juce jucie juise juse"
  , "latest": "lates latets latiest latist"
  , "laugh": "lagh lauf laught lugh"
  , "level": "leval"
  , "levels": "levals"
  , "liaison": "liaision liason"
  , "lieu": "liew"
  , "literature": "litriture"
  , "loans": "lones"
  , "locally": "localy"
  , "magnificent": "magnificnet magificent magnifcent magnifecent magnifiscant magnifisent magnificant"
  , "management": "managment"
  , "meant": "ment"
  , "minuscule": "miniscule"
  , "minutes": "muinets"
  , "monitoring": "monitering"
  , "necessary": "neccesary necesary neccesary necassary necassery neccasary"
  , "occurrence": "occurence occurence"
  , "often": "ofen offen offten ofton"
  , "opposite": "opisite oppasite oppesite oppisit oppisite opposit oppossite oppossitte"
  , "parallel": "paralel paralell parrallel parralell parrallell"
  , "particular": "particulaur"
  , "perhaps": "perhapse"
  , "personnel": "personnell"
  , "planned": "planed"
  , "poem": "poame"
  , "poems": "poims pomes"
  , "poetry": "poartry poertry poetre poety powetry"
  , "position": "possition"
  , "possible": "possable"
  , "pretend": "pertend protend prtend pritend"
  , "problem": "problam proble promblem proplen"
  , "pronunciation": "pronounciation"
  , "purple": "perple perpul poarple"
  , "questionnaire": "questionaire"
  , "really": "realy relley relly"
  , "receipt": "receit receite reciet recipt"
  , "receive": "recieve"
  , "refreshment": "reafreshment refreshmant refresment refressmunt"
  , "remember": "rember remeber rememmer rermember"
  , "remind": "remine remined"
  , "scarcely": "scarcly scarecly scarely scarsely"
  , "scissors": "scisors sissors"
  , "separate": "seperate"
  , "singular": "singulaur"
  , "someone": "somone"
  , "sources": "sorces"
  , "southern": "southen"
  , "special": "speaical specail specal speical"
  , "splendid": "spledid splended splened splended"
  , "standardizing": "stanerdizing"
  , "stomach": "stomac stomache stomec stumache"
  , "supersede": "supercede superceed"
  , "there": "ther"
  , "totally": "totaly"
  , "transferred": "transfred"
  , "transportability": "transportibility"
  , "triangular": "triangulaur"
  , "understand": "undersand undistand"
  , "unexpected": "unexpcted unexpeted unexspected"
  , "unfortunately": "unfortunatly"
  , "unique": "uneque"
  , "useful": "usefull"
  , "valuable": "valubale valuble"
  , "variable": "varable"
  , "variant": "vairiant"
  , "various": "vairious"
  , "visited": "fisited viseted vistid vistied"
  , "visitors": "vistors"
  , "voluntary": "volantry"
  , "voting": "voteing"
  , "wanted": "wantid wonted"
  , "whether": "wether"
  , "wrote": "rote wote"
  };
if(module && module.exports) { module.exports = PERF1; }